### ISSUE TITLE
cannot install qt-client

### ISSUE THREAD

**Issue by extremelydangerous** [xtuple/xtuple-server#289]
Hello, I built qt-client following the rules in the doc:
git clone...
git submodule --init --recursive
than...
cd openrpt;qmake;make
cd ../cvsimp;qmake;make
cd ..;gmake;make
it builds OK no erros, but all the install instruction in the Makefiles are empty so
the command: make install results nothing. the target "install:"  in the makefiles are EMPTY

Any new tip???

**Comment by gilmoskowitz** [comment]
`make install` does nothing by design. We have documented how to build the desktop client in a development environment only.

There is no simple way to build an _installable_ qt-client because there are so many shared library dependencies. You can still run the client that you built. Simply call it from a Terminal window or double-click on it from a file system browser. Make sure that you have a database server up and running, and an xTuple reference database loaded that you can connect to.

**Comment by extremelydangerous** [comment]
Ok... thanks,
the solution is to make a directory elsewere in the filesystem and run xtuple from there
